import {
  LifeChapter,
  AgeMilestone,
  PhotoItem,
  LoveQuality,
  LetterConfig,
  FinalSurpriseConfig,
} from '../types';

export const birthdayConfig = {
  herName: 'Bujjama',
  yourName: 'Siva',

  birthday: {
    date: '17 August',
  },

  relationship: {
    type: 'special person',
    yearsKnown: 4,
    firstMet: '2 March 2023',
  },

  memories: {
    firstConversation: 'Our first conversation started with a fight related to one issue.',
    firstOuting: 'Movie',
    sareeMemory: 'The first time Siva saw Bujjama in a saree — 22 March 2023.',
    funnyMemory: 'We somehow always forget something important whenever we go somewhere. 😂',
    bestTrip: 'Araku — our best trip.',
    support: 'When I was going through the process of getting a job, your support and positivity meant a lot to me.',
  },

  // Page 1 - The Surprise Begins
  page1: {
    intro: 'Hey, Bujjama ❤️',
    line1: 'I made something little for you...',
    line2: 'Because today is a little more special than usual.',
    dateBadge: '17 August ✨',
    buttonText: 'Open Your Surprise 💝',
  },

  // Page 2 - Happy Birthday Bujjama
  page2: {
    heading: 'Happy Birthday, Bujjama! 🎂❤️',
    date: '17 August',
    cakeSubtitle: 'A special day for a special person ✨',
    wishPrompt: 'Close your eyes and make a wish... ✨',
    wishButtonText: 'Make a Wish ✨',
    wishMessage1: "May this year bring you closer to everything you've been working and dreaming for.",
    wishMessage2: 'You deserve a year full of beautiful moments. ❤️',
    continueButtonText: "Bujjama's Journey →",
  },

  // Page 3 - Bujjama's Beautiful Chapters (Symbolic, NO photos)
  page3: {
    introSmallText: 'A journey through time...',
    introHeading: "Bujjama's Beautiful Chapters ✨",
    introSubtext: 'Every step, every smile, and every moment that shaped who you are today.',
    chapters: [
      {
        id: 'chapter-01',
        chapter: 'Chapter 01',
        age: 'Early Years',
        title: 'The Little One',
        description: 'An innocent beginning filled with curiosity, sweet smiles, and a gentle spirit stepping into the world.',
        quote: 'Every beautiful story begins with simple innocence.',
        icon: 'baby',
        tag: 'Sweet Beginnings 👶',
      },
      {
        id: 'chapter-02',
        chapter: 'Chapter 02',
        age: 'Growing Up',
        title: 'Growing & Discovering',
        description: 'Learning, discovering new interests, collecting simple joys, and slowly forming her own worldview.',
        quote: 'Collecting little moments and simple joys.',
        icon: 'book',
        tag: 'Curiosity & Discovery 🌱',
      },
      {
        id: 'chapter-03',
        chapter: 'Chapter 03',
        age: 'Teen Years',
        title: 'Finding Herself',
        description: 'New dreams taking shape, deeper thoughts, and beginning to discover her unique voice and inner confidence.',
        quote: 'Blossoming with grace and quiet strength.',
        icon: 'flower',
        tag: 'Blossoming Dreams 🌸',
      },
      {
        id: 'chapter-04',
        chapter: 'Chapter 04',
        age: 'Young Adult',
        title: 'Becoming Herself',
        description: 'Standing with poise, building resilience, and developing that calm, caring personality everyone admires.',
        quote: 'Stepping into her own warmth and identity.',
        icon: 'star',
        tag: 'Strength & Poise ✨',
      },
      {
        id: 'chapter-05',
        chapter: 'Chapter 05',
        age: 'New Beginnings',
        title: 'New Beginnings',
        description: 'Embracing fresh responsibilities, taking on new opportunities, and moving forward with steady determination.',
        quote: 'Facing every new challenge with courage.',
        icon: 'moon',
        tag: 'Fresh Horizons 🌙',
      },
      {
        id: 'chapter-06',
        chapter: 'Chapter 06',
        age: 'Present Day',
        title: 'Bujjama Today',
        description: 'Look at the wonderful person you are today. Kind-hearted, strong, witty, and effortlessly genuine.',
        quote: 'The wonderful person we are celebrating today. ❤️',
        icon: 'heart',
        tag: 'The Woman You Are ❤️',
        isSpecial: true,
      },
      {
        id: 'chapter-07',
        chapter: 'Chapter 07',
        age: 'The Future ✨',
        title: 'The Future',
        description: 'Exciting career milestones, new places waiting to be explored, and countless happy days yet to unfold.',
        quote: 'Your brightest chapters are still ahead. 🌟',
        icon: 'sparkles',
        tag: 'Bright Horizons 🌟',
        isSpecial: true,
      },
    ] as LifeChapter[],
    milestones: [
      { ageLabel: 'Early', subtitle: 'Sweet start', icon: '👶' },
      { ageLabel: 'Growing', subtitle: 'New steps', icon: '🌱' },
      { ageLabel: 'Dreams', subtitle: 'Finding voice', icon: '🌸' },
      { ageLabel: 'Grace', subtitle: 'Inner poise', icon: '✨' },
      { ageLabel: 'TODAY', subtitle: 'Radiant Bujjama', icon: '❤️' },
      { ageLabel: 'FUTURE', subtitle: 'Endless possibilities', icon: '🌟' },
    ] as AgeMilestone[],
    sharedStoryMilestone: {
      date: '2 March 2023',
      badge: 'A Special Milestone',
      label: 'And somewhere along the way... our story began.',
      punchline: 'And somehow, our story started with a fight. 😄',
      subtext: "Probably not the most ordinary beginning... but definitely one we'll remember.",
    },
    continueButtonText: 'See Her Memories →',
  },

  // Page 4 - Her Memories (ONLY Bujjama's Photos)
  herPhotos: [
    {
      id: 'photo-01',
      image: '',
      title: 'That Smile ❤️',
      caption: 'That smile ❤️',
      section: 'smile',
      layoutSpan: 'portrait',
    },
    {
      id: 'photo-02',
      image: '',
      title: 'Simply Bujjama',
      caption: 'Simply Bujjama.',
      section: 'moments',
      layoutSpan: 'standard',
    },
    {
      id: 'photo-03',
      image: '',
      title: 'One of My Favorites',
      caption: 'One of my favorites.',
      section: 'versions',
      layoutSpan: 'large',
    },
    {
      id: 'photo-04',
      image: '',
      title: 'Beautiful as Always',
      caption: 'Beautiful as always.',
      section: 'moments',
      layoutSpan: 'standard',
    },
    {
      id: 'photo-05',
      image: '',
      title: 'This One Feels Special',
      caption: 'This one feels special.',
      section: 'versions',
      layoutSpan: 'portrait',
    },
    {
      id: 'photo-06',
      image: '',
      title: 'Golden Moments',
      caption: 'That smile ❤️',
      section: 'smile',
      layoutSpan: 'landscape',
    },
  ] as PhotoItem[],

  page4: {
    introSmallText: 'Moments captured in frames...',
    heading: 'Her Memories 📸',
    subtext: 'A gallery dedicated entirely to Bujjama.',
    sectionSmileTitle: 'The Girl Behind The Smile ❤️',
    sectionMomentsTitle: 'Little Moments',
    sectionVersionsTitle: 'Different Versions of You',
    continueButtonText: 'What I Love About Bujjama →',
  },

  // Page 5 - What I Love About Bujjama (9 distinct interactive cards)
  qualities: [
    {
      id: 'qual-smile',
      number: '01',
      title: 'Your Smile ❤️',
      shortTag: 'Pure Sunshine',
      icon: 'smile',
      message: 'The kind of smile that effortlessly brightens any room and makes everything feel lighter.',
    },
    {
      id: 'qual-laugh',
      number: '02',
      title: 'Your Laugh',
      shortTag: 'Genuine & Infectious',
      icon: 'laugh',
      message: 'Pure, heartfelt, and impossible not to smile along with whenever you start laughing.',
    },
    {
      id: 'qual-caring',
      number: '03',
      title: 'Your Caring Nature',
      shortTag: 'Gentle Heart',
      icon: 'heart',
      message: 'One of the things I genuinely appreciate about you is how naturally you care. Sometimes it feels like you notice things before I even say them.',
    },
    {
      id: 'qual-talk',
      number: '04',
      title: 'The Way You Talk',
      shortTag: 'Effortless Connection',
      icon: 'message',
      message: "Whether it's discussing something important or just sharing random daily banter, talking to you is always something I look forward to.",
    },
    {
      id: 'qual-patience',
      number: '05',
      title: 'Your Patience',
      shortTag: 'Calm & Composed',
      icon: 'shield',
      message: 'The steady calm and patience you bring to conversations, even when situations get tricky.',
    },
    {
      id: 'qual-humor',
      number: '06',
      title: 'Your Sense of Humor',
      shortTag: 'Playful Wit',
      icon: 'sparkles',
      message: 'The quick wit and silly jokes that always catch me off guard and turn any ordinary moment into a funny one.',
    },
    {
      id: 'qual-determination',
      number: '07',
      title: 'Your Determination',
      shortTag: 'Quiet Strength',
      icon: 'compass',
      message: 'The quiet focus and resolve you show whenever you set your mind to something you care about.',
    },
    {
      id: 'qual-habits',
      number: '08',
      title: 'Your Little Habits',
      shortTag: 'Endearing Quirks',
      icon: 'gift',
      message: 'The small expressions, subtle gestures, and unique little quirks that are distinctly and beautifully Bujjama.',
    },
    {
      id: 'qual-support',
      number: '09',
      title: 'The Way You Support Me',
      shortTag: 'Steadfast Belief',
      icon: 'star',
      message: 'Your constant positivity and encouragement, especially during key moments when I needed it the most.',
    },
  ] as LoveQuality[],

  page5Ending: {
    heading: 'And honestly...',
    subtext: "I could keep listing things, but I'd probably never finish. ❤️",
    continueButtonText: 'Read A Letter From Siva ✉️ →',
  },

  // Page 6 - A Letter From Siva
  letter: {
    greeting: 'Dear Bujjama, ❤️',
    paragraphs: [
      'Happy Birthday!',
      "It's hard to believe it's already been 4 years since we came into each other's lives. Looking back to when we first met on March 2, 2023, it still makes me smile that our very first conversation actually started with a fight related to one issue. It probably wasn't the most ordinary beginning, but it turned into something truly special.",
      'From our first outing to the movie, to our trip to Araku—which remains the best trip we ever took—every memory we share holds a special place. I still remember the first time I saw you wearing a saree on March 22, 2023. And of course, the funny fact that no matter where we go, we somehow always manage to forget something important along the way. 😂',
      "Beyond the fun moments, what I treasure most is your genuine caring nature and that radiant smile. When I was going through the process of getting a job, your constant support and positivity meant the world to me and kept me going.",
      "As you celebrate your birthday today, my deepest wishes for you are success in your career, true happiness in everything you do, wonderful travel adventures, the strength to achieve all your dreams, countless beautiful memories, peace in your heart, and unwavering confidence in who you are.",
      'Thank you for being in my life and for simply being you.',
    ],
    closing: 'With lots of love,',
    signatureName: 'Siva ❤️',
    secretMessage: 'No matter what, this little corner of the web is always here to remind you how special you are. ❤️',
  } as LetterConfig,

  // Page 7 - Final Surprise & Birthday Ending (The Final Page)
  page7: {
    celebrationHeading: 'Happy Birthday, Bujjama! 🎂✨',
    celebrationSubtext: 'May this year bring you all the happiness, success, and smiles in the world.',
    finalWordsHeading: 'One Last Thing...',
    finalWordsMessage: 'No matter how much time passes, always remember how truly special you are.',
    replayButtonText: 'Replay the Journey ↻',
  },

  finalSurprise: {
    introLine1: 'You thought that was everything?',
    introLine2: 'Not quite... 👀',
    introButtonText: 'Open Final Surprise 🎁',
    oneLastThing: 'One last thing...',
    reminderMessage: 'I hope you always remember how special you are.',
    birthdayWishTitle: 'Happy Birthday, Bujjama ❤️',
    wishesList: [
      'Success in your career',
      'Endless happiness & smiles',
      'Exciting travel & adventures',
      'Achieving every dream you work for',
      'Countless beautiful memories',
      'Deep peace of mind',
      'Unshakable confidence in yourself',
    ],
    finalPrompt: 'Keep smiling. Keep dreaming. Keep being you. ❤️',
    closing: 'With love,',
    signatureName: 'Siva',
    footerText: 'Made with ❤️ by Siva, especially for Bujjama.',
    replayButtonText: 'Replay the Journey ↻',
  } as FinalSurpriseConfig,
};
